name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.6' # 使用这个操作来安装指定版本的Flutter

    - name: Install dependencies
      run: flutter pub get

    - name: Run
      run: flutter run -d linux

    - name: Build APK
      run: flutter build apk --release --target-platform=android-arm64
