name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: cirrusci/flutter:3.13.6

    steps:
    - uses: actions/checkout@v2

    - name: Get dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter run

    - name: Build APK
      run: flutter build apk --release --target-platform=android-arm64
